# Once you've generated the required secure environment variables
# uncomment the deploy section

sudo: true
language: clojure

env:
  global:
    - GITHUB_ORG=HughPowell
    - RELEASERS_NAME='Hugh Powell'
    # Use `travis encrypt MY_SECRET_ENV=super_secret`.
    # See here:https://docs.travis-ci.com/user/environment-variables/
    # "LEIN_USERNAME=[secure]"
    - secure: "ppcSXSjtJXpWFmo5eCG6HoRr6Ap6UE93vk9ZXYeEVjw9NqCL0cqWezBsdVdBh4rU6bod0PNw3wWlMBB7Z/QF6K0tYEyLNql5xF12wD0rjZYBFkV3XbxGm6Wugleu1QBDwaoPNhp5KUQiTV52dR3K+LrjasJoWdtSmSUvce9b6pGtBOWTzkP7FHPELNuNmdJgNznzOdKO1BNo1QKC3RhMhShC1HSkwMtkqeKElyYxY3GRP2kaIOQeR/sQBXSB+No69vmogGNs5RY47cGNjBJ+gwRJubsLgbIM1ZjAFvl8Xee6bAHfPcNk3dolZGDUOQUTA9/oJDd4H/vw+uBC4DNyfjP3SBsTGrAKYTtHr38M9ap5BS5UJHAEr+4Om1uqMvVKQ5bQxU5X0obpbqR2aix861o+71WYJSYimAgsKNay8A1PLE/QDqwH5oHh0oTxtcl/iYlwTwR5Ae36J9ecLa3lK8dpPFhVHvGy+/lsFK1BZBz6424iHHE5QZRqM/Wu6FaGW91BebCdua14igJFUDsjkTz7Mh6K5G2lGQsuWfnNO77Hgh2/kY4ugkoL1F23O7zFqlNAmLAKl4GCtfOBm4ywY71Y5+wK+xN2FnUfk3bKg1guYnk0E1hsVmq0pBZOoeow0tEmQGOoSWxHu7N6vWsubCWkhmmw190k67fn5yCcU70="
    # "LEIN_PASSWORD=[secure]"
    - secure: "iId5qRAbZaAB6xrMgTw0oaW7RPTRZHI8c5/NJoWlWt3/c4Kr3nLSgLJWop8oMZ/zKq66hUri5+z9HI8EpRm9bECEF9j7ZNEXxYigRWOHT1h90w6Louuv8Od77ziP6pTidgsvl71kB+q3GvuFgMTXYSsJRsczAYDMm10LU8qfjKo7ntPpM6qliAAw5/XrXPUTlavJ9RSFdeqJAr4lIo7Pu0XI++c1EPRYM2LSn/5mNkZzziACeM7pwF4M//rSXWHzExcIoiBIonZu4rzjLaY48PvCNFqRN/SlwMZfRMUM0tH7dbqY0wymEYzZNP0mFSgeVq5NjYwmg/xeRSAqKT9DjXfk6ET6ulj/uRwd4SeM4mi1gXQnl6mDeXFQpHNSZeb4paNZ+oJk7XAR4T6DX93VItAKmLFI6Z9IVe0y9fUr4g/tEi6Mc6BjIBPCcvGIJyhfsgepeyaKO6VJYi27lx+8fMfMOVXktMt5NUE1GnZyKNR/ozEiwNjRiUND6CFjHeGic0QiIBHrVpz45Na9S5gaNId67K1rwmv6eSNu0hAwdTNqC96vMKRJdBi1+rZ6zcmcioesB5jhoJBHGNUSCu2D7nJUORRG0h5oOZPjq9FKdKQ9jXwzbQTM/ObcuAK67BbjpznHIrWxVlQJHFSSunfri/nfjIYW00+0OW2zXCE2fI8="
    # "RELEASERS_EMAIL=[secure]"
    - secure: "NsNwH6bCBmM/Dz/qMV5SrocAiiNizmKYzdqqp5HmiTd/ShpfxUv9F8gphQEuM2a1Ef6175CuWvqnxMxW7ddB4C1RweYlC+XEa9hI0aupAX2Mb4yz7/dnf71xcfLe6KfF0uGdXB5jVTbMnU1TOuW6iL4zVedr1XOtdvyiFm32K0dOxfQDt6Rp7UFLVCl0XCqN2vkRnbxYhKOYht+hjbt2HTKTBCRj3NbZuRZP5680jPSF48lifVg1bx8Du5IZ/+g7mIqc+iUxlFKsa2fYkz5TviX/2c5x6Qic5KZsyTax6Nwa4uiyfB2YmzuWLfs/mjxy3sAboBwbSSIRECG2+6dYXYm3h0RSAMwDgBD1g88A/PrqapCCDEYFSxRYHa/hxD+9kb4yHpVYJIBqrvEgs8XIGzHNTpmF76fgA6IVCmGde6hcpsO2jrdTw6rToPtkJCUr10KHR7LGCI/po3+rnVYm+Sg5omB+wZPXsD+f+xc0ypyBPB+hrOVvgeIAAR6wWU24nOoS0vrbu58+wlvTdD2Ijy96fLeYHe0rj+PRFSGqk5MAImmTFuAcH8Irg+zg2UL3/TcmSW5NatNgnv4Y32SIllVbNwQebX98taedNlsvQW8KuQJe1sSYjzC/Ok2xGIJ5Vy1U1sfsL80ZSI1mREqD385WKUL6njy5yY2NZyK4KSk="
    # "GITHUB_TOKEN=[secure]"
    - secure: "ADYCB6mMCKI6N18vHts2wsjvj57uEpRfQa0CA4iPvEcK5K9PXOniwOhSblk/4ukhuF/ixsd6BuAKW8h54DYi0Gx4/fd1im4d057Cd51MeLunqpwfskCBWhJjYqXmIqHpsf9IUtlusp2STLY1wEZBQGOUuL/U8JAQB4Hjn+1b3A7qBg2vSKuD0KE9R9lePfGvmVov+xsRtvF7Ohgw5uWNkoqScYB1yd651l3rrInI7OOrcZERVYDfio9JJ95kZrOLNXIK/BWMsMlluG6v5ZcWHcmSour43e5410kX7EEqm2kPDvMJqfsWgK0xE4KCYO6yGCsFnP9yh5XjddIB8c9TP81khcIu38Jlj9pDEeS6YgUF1ao+0LGoQm0JVXdvaUZCnr2QnjZG7owB4RBKsmMJiSXWnd9kEml16O8MfmSABk7IbIRKs5BkD+8HkMh2X7uYdmJkfaob335HNtRJE+UECcGDQmeGAOLJRH/M0mvRPT+OPhxV2w3QPLtBV31KYN6qMttnQC0KrCihw+G1asZFOgIV7ZKh8rQiMGwTnDzzguyq2C+jB0EmIT9pdYMmSWbJ5FRM17C+Jl1AYoVZJqatloTSvStaCjO8uKGNzrF1Ihvs7mKljd+w23Kmhzyrzc0EhPjdKoxPEQHSXNElaYzvMgsIqNZXi9sTDsq75DfeqUc="

before_install: yes y | sudo lein upgrade

script: lein test

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy/travis_to_clojars.sh